#
# @package Ultimate phpBB SEO Friendly URL
# @version $$
# @copyright (c) 2017 phpBB SEO
# @license http://opensource.org/licenses/gpl-2.0.php GNU General Public License v2
#

services:
    phpbbseo.usu.core:
        class: phpbbseo\usu\core\core
        shared: true
        public: true
        arguments:
            - '@config'
            - '@request'
            - '@user'
            - '@auth'
            - '%core.root_path%'
            - '%core.php_ext%'

    phpbbseo.usu.listener:
        class: phpbbseo\usu\event\listener
        shared: true
        public: false
        arguments:
            - '@phpbbseo.usu.core'
            - '@config'
            - '@auth'
            - '@template'
            - '@user'
            - '@request'
            - '@dbal.conn'
            - '@language'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
